### ISSUE TITLE
Cannot convert a BigInt value to a number error after building prod env

### ISSUE THREAD

**Issue by Stenor5** [wevm/wagmi#2406]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

1.0.5

### Current Behavior

``` js
      try {
        const { hash } = await writeContract({
          ...accountManagerContractConfig,
          functionName: "load",
          args: [asset, ethAmount, encodedParams],
          value: parseEther("0.1"),
        });
        await waitForTransaction({ hash });
      } catch (error) {
        console.error(error);
      }
     
```
This code is working on dev env (React) but after building I have below errors.
```shell
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at l (toHex.ts:173:21)
    at encodeAbiParameters.ts:234:14
    at h (encodeAbiParameters.ts:98:12)
    at param (encodeAbiParameters.ts:272:27)
    at h (encodeAbiParameters.ts:86:12)
    at n.params (encodeAbiParameters.ts:68:25)
    at p (encodeAbiParameters.ts:43:26)
    at c (encodeFunctionData.ts:58:9)
    at simulateContract.ts:117:20
```

Please help me if someone has any idea.

**Comment by tmm** [comment]
Closing in favor of https://github.com/wagmi-dev/viem/issues/564
