### ISSUE TITLE
Uncaught Error: Cannot find module '@tanstack/query-core' 

### ISSUE THREAD

**Issue by netpoe** [wevm/wagmi#3497]
### Describe the bug

My NextJS app won't load after installing `wagmi@2.3.1`. This is the exact error: 

```
index.js:338 Uncaught Error: Cannot find module '@tanstack/query-core'
    at webpackMissingModule (call.js:6:50)
    at eval (call.js:6:145)
    at ./node_modules/@wagmi/core/dist/esm/query/call.js (index.js?ts=1705971056596:14203:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (query.js:76:72)
    at ./node_modules/@wagmi/core/dist/esm/exports/query.js (index.js?ts=1705971056596:14181:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (useBalance.js:5:75)
    at ./node_modules/wagmi/dist/esm/hooks/useBalance.js (index.js?ts=1705971056596:29273:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (index.js:96:78)
    at ./node_modules/wagmi/dist/esm/exports/index.js (index.js?ts=1705971056596:29240:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (EvmWalletSelectorContextController.tsx:12:63)
    at ./src/context/evm/wallet-selector/EvmWalletSelectorContextController.tsx (index.js?ts=1705971056596:6371:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (DashboardLayout.tsx:21:121)
    at ./src/layouts/dashboard-layout/DashboardLayout.tsx (index.js?ts=1705971056596:6492:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (index.tsx:10:98)
    at ./src/pages/index.tsx (index.js?ts=1705971056596:6503:1)
    at options.factory (webpack.js?ts=1705971056596:688:31)
    at __webpack_require__ (webpack.js?ts=1705971056596:37:33)
    at fn (webpack.js?ts=1705971056596:343:21)
    at eval (?67b5:5:16)
    at eval (route-loader.js:215:51)
```

This is the [link to the file EvmWalletSelectorContextController.tsx](https://github.com/Udit-takkar/pulsemarkets/blob/feat/typescript-interface/app/src/context/evm/wallet-selector/EvmWalletSelectorContextController.tsx) mentioned in the error, it does the main wagmi config and the Web3Modal with the alpha version [as suggested here](https://docs.walletconnect.com/web3modal/react/about?platform=wagmi).

This is the [package.json](https://github.com/Udit-takkar/pulsemarkets/blob/feat/typescript-interface/app/package.json#L42) with the latest versions as described in the [Wagmi docs](https://wagmi.sh/react/getting-started).

Lastly, the Wagmi config is loaded as a [React context here](https://github.com/Udit-takkar/pulsemarkets/blob/feat/typescript-interface/app/src/layouts/dashboard-layout/DashboardLayout.tsx#L42).

### Link to Minimal Reproducible Example

https://github.com/Udit-takkar/pulsemarkets/blob/feat/typescript-interface/app/src/context/evm/wallet-selector/EvmWalletSelectorContextController.tsx

### Wagmi Version

^2.3.1

### Viem Version

^2.4.1

### TypeScript Version

^5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

`"@tanstack/react-query": "^5.17.19",` should include "@tanstack/query-core", right? I also tried adding this package with `yarn add @tanstack/query-core` but still got the issue.

**Comment by tmm** [comment]
Please add a minimal reproduction. The current linked reproduction is not minimal.
