### ISSUE TITLE
Build error from publicProvider() on nextjs

### ISSUE THREAD

**Issue by theSchein** [wevm/wagmi#3530]
### Describe the bug

In the last few days I have been getting build errors from the wagmi components that were untouched for months. It is a TypeError from reading 'http' in the publicProvider method. I am running a nextjs 14 framework written in javascript.

My setup is boilerplate from the docs:

```
import { WagmiConfig, createConfig, configureChains, mainnet } from "wagmi";

import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";

import { CoinbaseWalletConnector } from "wagmi/connectors/coinbaseWallet";
import { InjectedConnector } from "wagmi/connectors/injected";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";


const { chains, publicClient, webSocketPublicClient } = configureChains(
    [mainnet],
    [alchemyProvider({ apiKey: process.env.ALCHMEY_API_KEY }), publicProvider()],
);

const config = createConfig({
    autoConnect: true,
    connectors: [
        new MetaMaskConnector({ chains }),
        new CoinbaseWalletConnector({
            chains,
            options: {
                appName: "wagmi",
            },
        }),
        new WalletConnectConnector({
            chains,
            options: {
                projectId: "...",
            },
        }),
        new InjectedConnector({
            chains,
            options: {
                name: "Injected",
                shimDisconnect: true,
            },
        }),
    ],
    publicClient,
    webSocketPublicClient,
});
```

### Steps To Reproduce

The issue is a consistently failed build from configuring wagmi. This is the error:

```
Collecting page data  ..TypeError: Cannot read properties of undefined (reading 'http')
    at file:///home/dov/Documents/app/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///home/dov/Documents/app/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at /home/dov/Documents/app/.next/server/pages/profile.js:3:453

> Build error occurred
Error: Failed to collect page data for /profile
    at /home/dov/Documents/app/node_modules/next/dist/build/utils.js:1258:15 {
  type: 'Error'
}

```

### Wagmi Version

1.3.10

### Viem Version

2.5.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by theSchein** [comment]
This was on me, I got lost in a version mismatch... closing issue
