### ISSUE TITLE
Error: To use QR modal, please install @walletconnect/modal package

### ISSUE THREAD

**Issue by trimn-1012** [wevm/wagmi#3775]
### Describe the bug

I am using nextjs 13.5.4 and wagmi 2.5.16. When I run yarn dev or yarn build at the terminal will show error message below
```
Error: To use QR modal, please install @walletconnect/modal package
    at I.initialize (/usr/src/app/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:7377)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async I.init (/usr/src/app/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:2743)
    at async initProvider (file:///usr/src/app/node_modules/@wagmi/connectors/dist/esm/walletConnect.js:102:24)
```
Node version: 20.9

### Wagmi Version

2.5.16

### Viem Version

2.9.5

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Anything else?

![Screenshot 2024-04-01 at 15 15 54](https://github.com/wevm/wagmi/assets/64879807/0be73a5f-8b43-47dc-a2b6-8e2246943194)

**Comment by trimn-1012** [comment]
This is my example: https://stackblitz.com/edit/stackblitz-starters-ssnbjx

**Comment by magiziz** [comment]
@trimn-1012 Try adding `ssr` true to your `createConfig`.

**Comment by jxom** [comment]
Seems like @magiziz's solution fixes it.
