### ISSUE TITLE
WalletConnectConnector issue: "@wagmi/core": "^1.4.13"

### ISSUE THREAD

**Issue by Nilbristi** [wevm/wagmi#3804]
### Describe the bug

I am using "@wagmi/core": "^1.4.13" with  Angular 16.

Everything was working fine. But today I suddenly noticed that WalletConnectConnector modal throwing an error while doing the scan via Trustwallet app (Android).
Iy is currently throwing the below error.

```
Error: Requested chains are not supported
    at index.es.js:1:3529
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:11083:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60) 
```

### Wagmi Version

"@wagmi/core": "^1.4.13"

### Viem Version

"viem": "^1.0.7",

### TypeScript Version

"typescript": "~5.0.2"

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
You should upgrade to v2, lots of bug fixes there.
https://wagmi.sh/react/guides/migrate-from-v1-to-v2
