### ISSUE TITLE
Using metaMask connector results in TypeError

### ISSUE THREAD

**Issue by 0xernesto** [wevm/wagmi#4193]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I'm building a React component library using `@wagmi/core 2.13.1` and `@wagmi/connectors 5.1.2`. i'm bundling the app using [rollup](https://rollupjs.org/), and testing locally using `npm link`.

Including the `metaMask` connector from `@wagmi/connectors` in the `connectors` array in `createConfig` results in the following TypeError.  All connectors work fine except for `metaMask`.

```
extractRpcUrls.js:12 Uncaught (in promise) 
TypeError: Cannot destructure property 'value' of 'undefined' as it is undefined.
    at eval (extractRpcUrls.js:12:30)
    at Array.map (<anonymous>)
    at extractRpcUrls (extractRpcUrls.js:12:23)
    at eval (metaMask.js:142:98)
    at Array.map (<anonymous>)
    at initProvider (metaMask.js:141:70)
    at async Object.getProvider (metaMask.js:157:28)
    at async Object.setup (metaMask.js:30:30)
```

Here is my config:
```typescript
const wagmiConfig = createConfig({
		chains: supportedChains as [Chain, ...Chain[]],
		connectors: [
			metaMask(), // <---- error goes away if I comment this out
			walletConnect({
				projectId: process.env.WC_PROJECT_ID!,
				metadata: {
					name: "My App",
					description:
						"My app description.",
					url: "https://myapp.xyz",
					icons: [myAppIcon],
				},
				qrModalOptions: {
					themeMode: "dark",
				},
			}),
			coinbaseWallet({
				appName: "My App",
				appLogoUrl: myAppIcon,
				darkMode: true,
				preference: "eoaOnly",
			}),
		],
		transports,
	});
```

It looks like the problem is in the `metaMask.ts` file:
```typescript
sdk = new MetaMaskSDK({
          _source: 'wagmi',
          // Workaround cast since MetaMask SDK does not support `'exactOptionalPropertyTypes'`
          ...(parameters as RemoveUndefined<typeof parameters>),
          readonlyRPCMap: Object.fromEntries(
            config.chains.map((chain) => {
              const [url] = extractRpcUrls({   // <----- This is the issue
                chain,
                transports: config.transports,
              })
              return [chain.id, url]
            }),
          ),
          dappMetadata: parameters.dappMetadata ?? {},
          useDeeplink: parameters.useDeeplink ?? true,
        })
```

### Steps To Reproduce

Dependencies:
```json
"dependencies": {
		"@reduxjs/toolkit": "^2.2.7",
		"@wagmi/connectors": "^5.1.2",
		"@wagmi/core": "^2.13.1",
		"react-redux": "^9.1.2",
		"redux": "^5.0.1",
		"viem": "^2.18.5"
	},
	"devDependencies": {
		"@babel/core": "^7.25.2",
		"@babel/preset-env": "^7.25.2",
		"@babel/preset-react": "^7.24.7",
		"@commitlint/cli": "^19.3.0",
		"@commitlint/config-conventional": "^19.2.2",
		"@rollup/plugin-babel": "^6.0.4",
		"@rollup/plugin-commonjs": "^26.0.1",
		"@rollup/plugin-image": "^3.0.3",
		"@rollup/plugin-json": "^6.1.0",
		"@rollup/plugin-node-resolve": "^15.2.3",
		"@rollup/plugin-typescript": "^11.1.6",
		"@semantic-release/changelog": "^6.0.3",
		"@semantic-release/git": "^10.0.1",
		"@testing-library/jest-dom": "^6.4.8",
		"@testing-library/react": "^16.0.0",
		"@types/jest": "^29.5.12",
		"@types/node": "^22.0.0",
		"@types/react": "^18.3.3",
		"@types/react-dom": "^18.3.0",
		"@typescript-eslint/eslint-plugin": "^7.18.0",
		"@typescript-eslint/parser": "^7.18.0",
		"autoprefixer": "^10.4.19",
		"commitizen": "^4.3.0",
		"cz-conventional-changelog": "^3.3.0",
		"cz-customizable": "^7.2.1",
		"eslint": "^8.57.0",
		"eslint-config-airbnb": "^19.0.4",
		"eslint-config-prettier": "^9.1.0",
		"eslint-import-resolver-typescript": "^3.6.1",
		"eslint-plugin-prettier": "^5.2.1",
		"eslint-plugin-react": "^7.35.0",
		"eslint-plugin-simple-import-sort": "^12.1.1",
		"husky": "^9.1.4",
		"identity-obj-proxy": "^3.0.0",
		"jest": "^29.7.0",
		"jest-environment-jsdom": "^29.7.0",
		"postcss": "^8.4.40",
		"prettier": "^3.3.3",
		"prettier-plugin-tailwindcss": "^0.6.5",
		"rollup": "^4.19.1",
		"rollup-plugin-dts": "^6.1.1",
		"rollup-plugin-node-polyfills": "^0.2.1",
		"rollup-plugin-peer-deps-external": "^2.2.4",
		"rollup-plugin-postcss": "^4.0.2",
		"semantic-release": "^24.0.0",
		"tailwindcss": "^3.4.7",
		"ts-jest": "^29.2.3",
		"tslib": "^2.6.3",
		"typescript": "^5.5.4"
	},
	"peerDependencies": {
		"react": "^18.3.1",
		"react-dom": "^18.3.1"
	}
```

### What Wagmi package(s) are you using?

@wagmi/connectors, @wagmi/core

### Wagmi Package(s) Version(s)

wagmi/core@2.13.1, wagmi/connectors@5.1.2

### Viem Version

2.18.5

### TypeScript Version

5.5.4

**Comment by mmzzli** [comment]
I also encountered the same problem, because I specified a custom chain in chains, but I did not modify the corresponding chain in transports below.
![image](https://github.com/user-attachments/assets/dd9f0c91-de4e-4d2b-bb54-3d7433eac88d)
